[package]
name = "earthlyls"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
tokio = { version = "1.36.0", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.22.2"
tree-sitter-earthfile = "0.1.2"
