[package]
name = "earthlyls"
version = "0.1.0"
edition = "2021"

[dependencies]
clean-path = "0.2.1"
dashmap = "5.5.3"
glob = "0.3.1"
ropey = "1.6.1"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.22.5"
tree-sitter-earthfile = "0.2.3"
